const translations = {
  fr: {navMethod:'La méthode',navJourney:'Le parcours',navMission:'Notre mission',notify:'Être prévenu',eyebrow:'Apprendre le tamoul devient enfin simple',heroTitle:'Ton tamoul.<br><em>Ton rythme.</em>',heroLead:'L’application mobile qui t’aide à lire, comprendre et parler tamoul avec des leçons courtes, des exercices concrets et une progression qui donne envie.',tryEarly:'Tester en avant-première',seeApp:'Voir l’app en action',community:'<strong>Conçu avec la communauté</strong><br>pour celles et ceux qui veulent renouer avec leur langue.',mobileKicker:'Une vraie expérience mobile',mobileTitle:'Ouvre l’app.<br><em>Continue ton voyage.</em>',mobileText:'Pas de cours compliqués ni de longues listes à mémoriser. Thimoli te montre quoi apprendre, te fait pratiquer, puis consolide ce que tu connais déjà.',methodKicker:'Une méthode qui donne envie',methodTitle:'Quelques minutes par jour.<br><em>Des progrès qui se voient.</em>',methodText:'Chaque leçon combine vocabulaire, écoute, lecture et répétition. Tu avances à ton rythme, sans cours interminables.',feature1Title:'Une habitude facile',feature1Text:'Quelques minutes suffisent pour avancer, même pendant une journée chargée.',feature2Title:'Un tamoul utile',feature2Text:'Écoute et pratique les mots que tu peux vraiment utiliser avec tes proches.',feature3Title:'De l’alphabet à l’oral',feature3Text:'Apprends à reconnaître, lire et prononcer sans te sentir dépassé.',journeyKicker:'Ton aventure',journeyTitle:'12 villages.<br><em>Un tamoul plus vivant.</em>',journeyText:'Chaque village ouvre un nouvel univers : les bases, la famille, la cuisine, la culture, les voyages… Plus tu apprends, plus ton monde évolue.',step1:'<strong>Commence simplement</strong>Les premiers sons, mots et expressions.',step2:'<strong>Prends confiance</strong>Comprends et construis tes phrases.',step3:'<strong>Fais vivre la langue</strong>Parle avec plus de naturel au quotidien.',explore:'Explorer le prototype',whyKicker:'Pourquoi Thimoli ?',whyTitle:'Apprendre une langue,<br>c’est aussi <em>retrouver un lien.</em>',whyText:'Beaucoup ont grandi en comprenant quelques mots sans jamais oser parler. Thimoli est né pour rendre ce chemin plus accessible, plus moderne et plus fier.',quote:'La langue tamoule ne devrait pas sembler inaccessible à la génération qui veut la retrouver.',soon:'Bientôt sur mobile',waitTitle:'La première version<br>se prépare avec toi.',waitText:'Inscris-toi pour tester Thimoli avant sa sortie et nous aider à construire l’app dont la communauté a besoin.',notifyMe:'Me prévenir',noSpam:'Pas de spam. Seulement les nouvelles importantes de Thimoli.',footerTagline:'Apprendre le tamoul. Faire vivre le lien.',privacy:'Confidentialité',legal:'© 2026 Thimoli. Fait avec soin pour la communauté tamoule.'},
  en: {navMethod:'The method',navJourney:'The journey',navMission:'Our mission',notify:'Get notified',eyebrow:'Learning Tamil is finally simple',heroTitle:'Your Tamil.<br><em>Your pace.</em>',heroLead:'The mobile app that helps you read, understand and speak Tamil through short lessons, practical exercises and motivating progress.',tryEarly:'Get early access',seeApp:'See the app in action',community:'<strong>Built with the community</strong><br>for everyone who wants to reconnect with their language.',mobileKicker:'A true mobile experience',mobileTitle:'Open the app.<br><em>Continue your journey.</em>',mobileText:'No complicated courses or endless lists to memorise. Thimoli shows you what to learn, helps you practise and strengthens what you already know.',methodKicker:'A method that keeps you motivated',methodTitle:'A few minutes a day.<br><em>Progress you can see.</em>',methodText:'Every lesson blends vocabulary, listening, reading and repetition. Move at your own pace, without endless classes.',feature1Title:'An easy habit',feature1Text:'A few minutes are enough to make progress, even on a busy day.',feature2Title:'Useful Tamil',feature2Text:'Listen to and practise words you can genuinely use with your loved ones.',feature3Title:'From alphabet to conversation',feature3Text:'Learn to recognise, read and pronounce Tamil without feeling overwhelmed.',journeyKicker:'Your adventure',journeyTitle:'12 villages.<br><em>A more vibrant Tamil.</em>',journeyText:'Each village opens a new world: basics, family, food, culture and travel. The more you learn, the more your world evolves.',step1:'<strong>Start simply</strong>Your first sounds, words and expressions.',step2:'<strong>Build confidence</strong>Understand and build your own sentences.',step3:'<strong>Bring the language to life</strong>Speak more naturally every day.',explore:'Explore the prototype',whyKicker:'Why Thimoli?',whyTitle:'Learning a language<br>also means <em>reconnecting.</em>',whyText:'Many grew up understanding a few words without ever daring to speak. Thimoli makes that journey more accessible, modern and empowering.',quote:'Tamil should not feel inaccessible to the generation that wants to reclaim it.',soon:'Coming soon to mobile',waitTitle:'The first version<br>is being built with you.',waitText:'Sign up to test Thimoli before launch and help us build the app the community needs.',notifyMe:'Notify me',noSpam:'No spam. Only important Thimoli news.',footerTagline:'Learn Tamil. Keep the connection alive.',privacy:'Privacy',legal:'© 2026 Thimoli. Made with care for the Tamil community.'},
  de: {navMethod:'Die Methode',navJourney:'Der Lernweg',navMission:'Unsere Mission',notify:'Benachrichtigen',eyebrow:'Tamil lernen wird endlich einfach',heroTitle:'Dein Tamil.<br><em>Dein Tempo.</em>',heroLead:'Die mobile App, mit der du Tamil durch kurze Lektionen, praktische Übungen und motivierende Fortschritte lesen, verstehen und sprechen lernst.',tryEarly:'Frühzugang testen',seeApp:'App in Aktion ansehen',community:'<strong>Mit der Community entwickelt</strong><br>für alle, die sich wieder mit ihrer Sprache verbinden möchten.',mobileKicker:'Ein echtes mobiles Erlebnis',mobileTitle:'Öffne die App.<br><em>Setze deine Reise fort.</em>',mobileText:'Keine komplizierten Kurse und keine endlosen Wortlisten. Thimoli zeigt dir, was du lernen solltest, lässt dich üben und festigt dein Wissen.',methodKicker:'Eine motivierende Methode',methodTitle:'Ein paar Minuten täglich.<br><em>Sichtbare Fortschritte.</em>',methodText:'Jede Lektion verbindet Wortschatz, Hören, Lesen und Wiederholung. Du lernst in deinem Tempo, ohne endlose Kurse.',feature1Title:'Eine einfache Gewohnheit',feature1Text:'Schon wenige Minuten reichen aus, um auch an einem vollen Tag Fortschritte zu machen.',feature2Title:'Nützliches Tamil',feature2Text:'Höre und übe Wörter, die du wirklich mit deinen Liebsten verwenden kannst.',feature3Title:'Vom Alphabet zum Sprechen',feature3Text:'Lerne Tamil zu erkennen, zu lesen und auszusprechen, ohne dich überfordert zu fühlen.',journeyKicker:'Dein Abenteuer',journeyTitle:'12 Dörfer.<br><em>Lebendigeres Tamil.</em>',journeyText:'Jedes Dorf eröffnet eine neue Welt: Grundlagen, Familie, Küche, Kultur und Reisen. Je mehr du lernst, desto größer wird deine Welt.',step1:'<strong>Einfach beginnen</strong>Die ersten Laute, Wörter und Ausdrücke.',step2:'<strong>Sicherheit gewinnen</strong>Sätze verstehen und selbst bilden.',step3:'<strong>Die Sprache leben</strong>Im Alltag natürlicher sprechen.',explore:'Prototyp entdecken',whyKicker:'Warum Thimoli?',whyTitle:'Eine Sprache lernen heißt auch,<br><em>eine Verbindung wiederzufinden.</em>',whyText:'Viele sind mit einigen verstandenen Wörtern aufgewachsen, ohne selbst zu sprechen. Thimoli macht diesen Weg zugänglicher, moderner und selbstbewusster.',quote:'Tamil sollte für die Generation, die es wiederentdecken möchte, nicht unerreichbar wirken.',soon:'Demnächst auf Mobilgeräten',waitTitle:'Die erste Version<br>entsteht gemeinsam mit dir.',waitText:'Melde dich an, teste Thimoli vor dem Start und hilf uns, die App zu entwickeln, die die Community braucht.',notifyMe:'Benachrichtigen',noSpam:'Kein Spam. Nur wichtige Neuigkeiten von Thimoli.',footerTagline:'Tamil lernen. Die Verbindung lebendig halten.',privacy:'Datenschutz',legal:'© 2026 Thimoli. Mit Sorgfalt für die tamilische Community entwickelt.'},
  es: {navMethod:'El método',navJourney:'El recorrido',navMission:'Nuestra misión',notify:'Avisarme',eyebrow:'Aprender tamil por fin es sencillo',heroTitle:'Tu tamil.<br><em>A tu ritmo.</em>',heroLead:'La aplicación móvil que te ayuda a leer, comprender y hablar tamil con lecciones cortas, ejercicios prácticos y un progreso motivador.',tryEarly:'Probar antes del lanzamiento',seeApp:'Ver la app en acción',community:'<strong>Creada con la comunidad</strong><br>para quienes quieren reconectar con su lengua.',mobileKicker:'Una verdadera experiencia móvil',mobileTitle:'Abre la app.<br><em>Continúa tu viaje.</em>',mobileText:'Sin cursos complicados ni largas listas para memorizar. Thimoli te muestra qué aprender, te ayuda a practicar y consolida lo que ya sabes.',methodKicker:'Un método que motiva',methodTitle:'Unos minutos al día.<br><em>Un progreso visible.</em>',methodText:'Cada lección combina vocabulario, escucha, lectura y repetición. Avanzas a tu ritmo, sin clases interminables.',feature1Title:'Un hábito fácil',feature1Text:'Unos minutos bastan para avanzar, incluso en un día muy ocupado.',feature2Title:'Tamil útil',feature2Text:'Escucha y practica palabras que realmente puedes usar con tus seres queridos.',feature3Title:'Del alfabeto a la conversación',feature3Text:'Aprende a reconocer, leer y pronunciar tamil sin sentirte abrumado.',journeyKicker:'Tu aventura',journeyTitle:'12 aldeas.<br><em>Un tamil más vivo.</em>',journeyText:'Cada aldea abre un mundo nuevo: las bases, la familia, la cocina, la cultura y los viajes. Cuanto más aprendes, más evoluciona tu mundo.',step1:'<strong>Empieza fácilmente</strong>Los primeros sonidos, palabras y expresiones.',step2:'<strong>Gana confianza</strong>Comprende y construye tus propias frases.',step3:'<strong>Da vida al idioma</strong>Habla con más naturalidad cada día.',explore:'Explorar el prototipo',whyKicker:'¿Por qué Thimoli?',whyTitle:'Aprender una lengua<br>también es <em>recuperar un vínculo.</em>',whyText:'Muchas personas crecieron entendiendo algunas palabras sin atreverse a hablar. Thimoli hace este camino más accesible, moderno y motivo de orgullo.',quote:'El tamil no debería parecer inaccesible para la generación que quiere recuperarlo.',soon:'Muy pronto en móvil',waitTitle:'La primera versión<br>se prepara contigo.',waitText:'Regístrate para probar Thimoli antes del lanzamiento y ayúdanos a crear la aplicación que la comunidad necesita.',notifyMe:'Avisarme',noSpam:'Sin spam. Solo las noticias importantes de Thimoli.',footerTagline:'Aprender tamil. Mantener vivo el vínculo.',privacy:'Privacidad',legal:'© 2026 Thimoli. Creado con cariño para la comunidad tamil.'}
};

const languageSelect = document.getElementById('language');
function setLanguage(language) {
  const lang = translations[language] ? language : 'fr';
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach((element) => {
    const value = translations[lang][element.dataset.i18n];
    if (value) element.innerHTML = value;
  });
  const captions = {
    fr:['Ton village','Des exercices simples','Un retour immédiat','Tes progrès'],
    en:['Your village','Simple exercises','Instant feedback','Your progress'],
    de:['Dein Dorf','Einfache Übungen','Sofortiges Feedback','Dein Fortschritt'],
    es:['Tu aldea','Ejercicios sencillos','Respuesta inmediata','Tu progreso']
  };
  document.querySelectorAll('[data-i18n^="caption"]').forEach((element, index) => element.textContent = captions[lang][index]);
  const sliderHints = {fr:'← Fais glisser →',en:'← Swipe →',de:'← Wischen →',es:'← Desliza →'};
  document.getElementById('slider-hint').textContent = sliderHints[lang];
  languageSelect.value = lang;
  localStorage.setItem('thimoli-language', lang);
}
languageSelect.addEventListener('change', (event) => setLanguage(event.target.value));
setLanguage(localStorage.getItem('thimoli-language') || 'fr');

const observer = new IntersectionObserver((entries) => {
  entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add('visible'));
}, { threshold: .12 });
document.querySelectorAll('.reveal').forEach((el) => observer.observe(el));

document.getElementById('waitlist-form').addEventListener('submit', (event) => {
  event.preventDefault();
  const email = document.getElementById('email');
  const note = document.getElementById('form-note');
  const messages = {fr:'Merci ! Ton inscription est bien enregistrée.',en:'Thank you! Your registration is confirmed.',de:'Danke! Deine Anmeldung wurde gespeichert.',es:'¡Gracias! Tu inscripción está confirmada.'};
  note.textContent = messages[languageSelect.value];
  note.classList.add('success');
  email.value = '';
});

